/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secure.sms;
import javax.swing.JOptionPane;
import all_requests.Request;
import all_requests.RequestDAOImpl;
import session.LoggedInUser;
import users.User;
/**
 *
 * @author Lenovo
 */
public class PersonnelGUI extends javax.swing.JFrame {
    RequestDAOImpl requestDAOImpl = new RequestDAOImpl();
    /**
     * Creates new form PersonnelGUI
     */
    public PersonnelGUI() {
        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        supplyRequestInfoTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        supplyDescriptionTF = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        supplyLocationTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        supplyPriorityCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        supplyRequestedByTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        supplyQuantityTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        supplyPurposeTF = new javax.swing.JTextArea();
        supplySubmitBTN = new javax.swing.JButton();
        supplyResetBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        supplyUser_idTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        serviceRequestInfoTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviceDescriptionTF = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        serviceLocationTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        servicePriorityCB = new javax.swing.JComboBox<>();
        serviceSubmitBTN = new javax.swing.JButton();
        serviceResetBTN = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        serviceUser_idTF = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User_ID", "Requested By", "Request Info", "Type", "Created", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dashboard", jPanel4);

        supplyRequestInfoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplyRequestInfoTFActionPerformed(evt);
            }
        });

        jLabel14.setText("Request Info");

        jLabel15.setText("Description");

        supplyDescriptionTF.setColumns(20);
        supplyDescriptionTF.setRows(5);
        jScrollPane4.setViewportView(supplyDescriptionTF);

        jLabel16.setText("Location:");

        jLabel10.setText("Priority:");

        supplyPriorityCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High", "Urgent" }));

        jLabel1.setText("Requested by:");

        jLabel3.setText("Quantity");

        jLabel4.setText("Purpose/Reason");

        supplyPurposeTF.setColumns(20);
        supplyPurposeTF.setRows(5);
        jScrollPane5.setViewportView(supplyPurposeTF);

        supplySubmitBTN.setText("Submit");
        supplySubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplySubmitBTNActionPerformed(evt);
            }
        });

        supplyResetBTN.setText("Reset");
        supplyResetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplyResetBTNActionPerformed(evt);
            }
        });

        jLabel2.setText("User_id:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(supplyLocationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(supplyRequestedByTF))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(supplyPriorityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(supplyUser_idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplyRequestInfoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(supplyQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(90, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(supplySubmitBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supplyResetBTN)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplyRequestInfoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplyQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(supplyLocationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(supplyPriorityCB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(supplyRequestedByTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(supplyUser_idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplySubmitBTN)
                    .addComponent(supplyResetBTN))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Supplies", jPanel3);

        jLabel5.setText("Request Info");

        jLabel6.setText("Description");

        serviceDescriptionTF.setColumns(20);
        serviceDescriptionTF.setRows(5);
        jScrollPane2.setViewportView(serviceDescriptionTF);

        jLabel7.setText("Location");

        jLabel9.setText("Priority:");

        servicePriorityCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High", "Urgent" }));

        serviceSubmitBTN.setText("Submit");
        serviceSubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceSubmitBTNActionPerformed(evt);
            }
        });

        serviceResetBTN.setText("Reset");
        serviceResetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceResetBTNActionPerformed(evt);
            }
        });

        jLabel12.setText("User_id:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(serviceRequestInfoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceLocationTF)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jLabel8))
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(servicePriorityCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(serviceUser_idTF))))
                                .addGap(0, 108, Short.MAX_VALUE)))))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(serviceSubmitBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceResetBTN)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceRequestInfoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(serviceLocationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(servicePriorityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(serviceUser_idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceSubmitBTN)
                    .addComponent(serviceResetBTN))
                .addGap(24, 24, 24))
        );

        jTabbedPane2.addTab("Services", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Submit Request", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Supply List", jPanel6);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Notification", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Log-out", jPanel9);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void serviceResetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceResetBTNActionPerformed
        serviceUser_idTF.setText("");
        serviceRequestInfoTF.setText("");
        serviceDescriptionTF.setText("");
        serviceLocationTF.setText("");
        servicePriorityCB.setToolTipText("");

    }//GEN-LAST:event_serviceResetBTNActionPerformed

    private void serviceSubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceSubmitBTNActionPerformed
        // TODO add your handling code here:

        /*String userIdText = serviceUser_idTF.getText().trim();

        int user_id = Integer.parseInt(userIdText);
        String request_info = serviceRequestInfoTF.getText();
        String description = serviceDescriptionTF.getText();
        String location = serviceLocationTF.getText();
        String priority = (servicePriorityCB.getSelectedItem() != null) ? servicePriorityCB.getSelectedItem().toString() : "";

        if (user_id == 0 || request_info.equals("") || description.equals("") || location.equals("") || priority.equals("")) {
            JOptionPane.showMessageDialog(null,
                "Please complete all fields.",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(serviceSubmitBTN.getText().equals("Submit")){
            int option = JOptionPane.showConfirmDialog(null,
                "This will save the entries currently on the form. Are you sure?",
                "Confirmation",
                JOptionPane.OK_CANCEL_OPTION);

            if(option == JOptionPane.OK_OPTION){
                Service service = new Service(0, user_id, request_info, description, location, priority,"");

                if(serviceDAOImpl.create(service)){
                    JOptionPane.showMessageDialog(null,
                        "Your request was successfully submitted!",
                        "Message",
                        JOptionPane.INFORMATION_MESSAGE);

                    serviceUser_idTF.setText("");
                    serviceRequestInfoTF.setText("");
                    serviceDescriptionTF.setText("");
                    serviceLocationTF.setText("");
                    servicePriorityCB.setSelectedIndex(0);

                } else {
                    JOptionPane.showMessageDialog(null,
                        "Your request was not submitted",
                        "Message",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } */

        String userIdText = serviceUser_idTF.getText().trim();

        if (userIdText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "User ID cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String request_info = serviceRequestInfoTF.getText();
        String description = serviceDescriptionTF.getText();
        String location = serviceLocationTF.getText();
        String priority = (servicePriorityCB.getSelectedItem() != null) ? servicePriorityCB.getSelectedItem().toString() : "";

        if (request_info.isEmpty() || description.isEmpty() || location.isEmpty() || priority.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please complete all fields.", "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int option = JOptionPane.showConfirmDialog(null, "This will save the service request. Are you sure?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);

        if (option == JOptionPane.OK_OPTION) {
            int user_id = LoggedInUser.getUserId();
            Request request = new Request(0,user_id,request_info,"Service","",description,"","",location,priority,"");

            if (requestDAOImpl.create(request)) {
                JOptionPane.showMessageDialog(null, "Service request submitted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                serviceRequestInfoTF.setText("");
                serviceDescriptionTF.setText("");
                serviceLocationTF.setText("");
                servicePriorityCB.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "Service request failed to submit.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_serviceSubmitBTNActionPerformed

    private void supplyResetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplyResetBTNActionPerformed
        supplyUser_idTF.setText("");
        supplyRequestInfoTF.setText("");
        supplyQuantityTF.setText("");
        supplyDescriptionTF.setText("");
        supplyPurposeTF.setText("");
        supplyLocationTF.setText("");
        supplyRequestedByTF.setText("");
        supplyPriorityCB.setToolTipText("");
    }//GEN-LAST:event_supplyResetBTNActionPerformed

    private void supplySubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplySubmitBTNActionPerformed

        String userIdText = supplyUser_idTF.getText().trim();

        if (userIdText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "User ID cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String request_info = supplyRequestInfoTF.getText();
        String quantity = supplyQuantityTF.getText();
        String description = supplyDescriptionTF.getText();
        String purpose = supplyPurposeTF.getText();
        String requested_by = supplyRequestedByTF.getText();
        String location = supplyLocationTF.getText();
        String priority = (supplyPriorityCB.getSelectedItem() != null) ? supplyPriorityCB.getSelectedItem().toString() : "";

        if (request_info.isEmpty() || quantity.isEmpty() || purpose.isEmpty() || requested_by.isEmpty() ||location.isEmpty()|| priority.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please complete all fields.", "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int option = JOptionPane.showConfirmDialog(null, "This will save the supply request. Are you sure?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);

        if (option == JOptionPane.OK_OPTION) {
            int user_id = LoggedInUser.getUserId();
            Request request = new Request(0, user_id, request_info, "Supply", quantity, description, purpose,requested_by, location, priority, "");

            if (requestDAOImpl.create(request)) {
                JOptionPane.showMessageDialog(null, "Supply request submitted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                supplyRequestInfoTF.setText("");
                supplyQuantityTF.setText("");
                supplyDescriptionTF.setText("");
                supplyPurposeTF.setText("");
                supplyRequestedByTF.setText("");
                supplyLocationTF.setText("");
                supplyPriorityCB.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "Supply request failed to submit.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        /*String userIdText = supplyUser_idTF.getText().trim();

        int user_id = Integer.parseInt(userIdText);
        String request_info = supplyRequestInfoTF.getText();
        int quantity = Integer.parseInt(supplyQuantityTF.getText());
        String description = supplyDescriptionTF.getText();
        String purpose= supplyPurposeTF.getText();
        String location = supplyLocationTF.getText();
        String requested_by = supplyRequestedTF.getText();
        String priority = (supplyPriorityCB.getSelectedItem() != null) ? supplyPriorityCB.getSelectedItem().toString() : "";
        String date_of_use = supplyDateofuseTF.getText();

        if (user_id == 0 || request_info.equals("") || quantity ==0||description.equals("") || purpose.equals("")||location.equals("") || requested_by.equals("")||priority.equals("")|| date_of_use.equals("")) {
            JOptionPane.showMessageDialog(null,
                "Please complete all fields.",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(supplySubmitBTN.getText().equals("Submit")){
            int option = JOptionPane.showConfirmDialog(null,
                "This will save the entries currently on the form. Are you sure?",
                "Confirmation",
                JOptionPane.OK_CANCEL_OPTION);

            if(option == JOptionPane.OK_OPTION){
                Supply supply = new Supply(0, user_id, request_info,quantity, description,purpose, location,requested_by, priority,date_of_use,"");

                if(supplyDAOImpl.create(supply)){
                    JOptionPane.showMessageDialog(null,
                        "Your request was successfully submitted!",
                        "Message",
                        JOptionPane.INFORMATION_MESSAGE);

                    // Optional: Clear fields after success
                    serviceUser_idTF.setText("");
                    serviceRequestInfoTF.setText("");
                    serviceDescriptionTF.setText("");
                    serviceLocationTF.setText("");
                    servicePriorityCB.setSelectedIndex(0);

                } else {
                    JOptionPane.showMessageDialog(null,
                        "Your request was not submitted",
                        "Message",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }*/
    }//GEN-LAST:event_supplySubmitBTNActionPerformed

    private void supplyRequestInfoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplyRequestInfoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplyRequestInfoTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea serviceDescriptionTF;
    private javax.swing.JTextField serviceLocationTF;
    private javax.swing.JComboBox<String> servicePriorityCB;
    private javax.swing.JTextField serviceRequestInfoTF;
    private javax.swing.JButton serviceResetBTN;
    private javax.swing.JButton serviceSubmitBTN;
    private javax.swing.JTextField serviceUser_idTF;
    private javax.swing.JTextArea supplyDescriptionTF;
    private javax.swing.JTextField supplyLocationTF;
    private javax.swing.JComboBox<String> supplyPriorityCB;
    private javax.swing.JTextArea supplyPurposeTF;
    private javax.swing.JTextField supplyQuantityTF;
    private javax.swing.JTextField supplyRequestInfoTF;
    private javax.swing.JTextField supplyRequestedByTF;
    private javax.swing.JButton supplyResetBTN;
    private javax.swing.JButton supplySubmitBTN;
    private javax.swing.JTextField supplyUser_idTF;
    // End of variables declaration//GEN-END:variables
}
